import Head from "next/head";
import Banner from "../components/Banner";
import Page from "../components/Page";
import MultiSlide from "../components/Slider/MultiSlide";
import SingleSlide from "../components/Slider/SingleSlide";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <MultiSlide />
      <SingleSlide />
      <Page />
    </div>
  );
}
